import{a as L,i as u,S as b}from"./assets/vendor-CNqCr-V-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const v="53081449-0d1e064c0b2c3f50b0b9354c8",w="https://pixabay.com/api/";async function p(o,r=1,i=20){try{return(await L.get(w,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:i}})).data}catch(s){throw console.error("Fetch error:",s),s}}function g(o){return o.map(({webformatURL:r,largeImageURL:i,tags:s,likes:e,views:t,comments:a,downloads:y})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${r}" alt="${s}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes</b> ${e}</p>
          <p><b>Views</b> ${t}</p>
          <p><b>Comments</b> ${a}</p>
          <p><b>Downloads</b> ${y}</p>
        </div>
      </li>`).join("")}const S=document.querySelector(".search-form"),h=document.querySelector(".gallery"),n=document.querySelector(".load-more"),c=document.querySelector(".loader");let d="",l=1;const f=20;let m;S.addEventListener("submit",E);n.addEventListener("click",q);async function E(o){if(o.preventDefault(),h.innerHTML="",l=1,d=o.target.elements.searchQuery.value.trim(),!!d){c.classList.remove("hidden"),n.classList.add("hidden");try{const r=await p(d,l,f);if(r.hits.length===0){u.error({title:"Error",message:"Sorry, no images found. Try again!"}),c.classList.add("hidden");return}h.innerHTML=g(r.hits),c.classList.add("hidden"),n.classList.remove("hidden"),m=new b(".gallery a"),m.refresh(),r.totalHits<=f&&n.classList.add("hidden")}catch{u.error({title:"Error",message:"Something went wrong!"})}}}async function q(){l+=1,c.classList.remove("hidden");try{const o=await p(d,l,f);h.insertAdjacentHTML("beforeend",g(o.hits)),m.refresh();const r=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"}),l*f>=o.totalHits&&(n.classList.add("hidden"),u.info({message:"We're sorry, but you've reached the end of search results."}))}catch{u.error({title:"Error",message:"Failed to load more images"})}finally{c.classList.add("hidden")}}
//# sourceMappingURL=index.js.map
